services:
  ollama_rocm64:
    build:
      context: .
      dockerfile: Dockerfile_rocm64_ollama
    container_name: rocm64_ollama_090
    ports:
      - "8080:8080"
      - "11434:11434"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - "video"
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    environment:
      HSA_OVERRIDE_GFX_VERSION: "8.0.3"
      ROC_ENABLE_PRE_VEGA: "1"
      HIP_VISIBLE_DEVICES: "0"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
