services:
  ollama_rom64:
    image:
      build:
        context: .
        dockerfile: Dockerfile_rocm64_ollama
    container_name: rocm64_ollama_090
    ports:
      - "8080:8080"
      - "11434:11434"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - "video"
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
     - ollama_data:/root/.ollama

volumes:
  ollama_data: